<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>AsistentIno</RootNamespace>
	<AssemblyName>AsistentIno.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\AsistentIno.Core\AsistentIno.Core.csproj" />
  </ItemGroup>

</Project>
